language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=b9ca1685f0204ad2c69a9592b073760f7f32a864e1be5359a29afc1af2ef7476
matrix:
  include:
    - node_js: '12'
cache:
  directories:
    - node_modules
install: npm i
after_success: npm run coverage
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - './cc-test-reporter before-build'
script:
  - npm run test
after_script:
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESUL'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: aDzN7eFofudh6amx5gUZLrVVsvdk1VIhrVh0gASdi8JWTz1XCSH5efkJ5WDrG5tmSdwTMUTeGldFt4UGGVNQfWUxv1P94EKnwpVYJ5aGU9JHH80a9BGbXIgIa7mGARWwsfAMRILjab5C0N0atVhvHNIh5w8rRLFg4Mh4iGSQ4zZ91WvLclSRAWmn7GqoN+SlbaB+ANocOCTilf8pYbqY8pDPVgEVMSI2R2IhOyKoM24JJNPa1w/Gy13dk+s30ittCCEnNrP38DkTnlnmame+XgnPg7jIBnE+x/J96kUlfuWYbhdylo6aaaDMHPX+ZPzgIqYzmeP02UGq0oyf3Q6+js33MUj05xiFtPsiy6IZfLoJrGobgKyp0QkoTgee7RbAemti6E5zeiYIUK3QGiiHTv+jjswMporH9sWycvh+ky+P9Q7KEHkn0HcXWdaVfLTaIOz7U2mdoPlF/RqmlZ9olIcY03cUMndV8bhwsFIUyvyK2+Ep93AT/mxTo8gZ3TKfnT70L0pdV2kWbkERHexLthXM1tu5UyCPiNQe0si9Jd2LIKZr0madiQzFuIddEzwIaeQPni9CS0wGFeg24xIvZ43bIUHqp2H1Ngvh0pKVFyu+kBgvvETEpACzA+/MuAuRM+IJSP8Ueq6mm4ciEibZxL/QCNDpbvgA/9Yh/TcH+Gg=
  app: repair-cycle-api
  skip_cleanup: true
